# Generated by Django 3.2.20 on 2023-12-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discreption',
            new_name='description',
        ),
    ]
